### ISSUE TITLE
An error appears in the script selector

### ISSUE THREAD

**Issue by rltgjqmcpgjadyd** [Koishi-Star/Euler-Smea-Dyn-Sampler#22]
![스크린샷 2024-04-16 194551](https://github.com/Koishi-Star/Euler-Smea-Dyn-Sampler/assets/115572150/a7a610ed-dab0-4927-a7c6-c4394d0db883)

There's nothing wrong with the sampler behavior, but it's annoying.

**Comment by DenOfEquity** [comment]
Seems like this can be fixed by adding:
```
            def show(self, is_img2img):
                return False
```
to the **SMEA** class in *scripts/smea.py*.
